# This workflow hard-tags and exports soft-tagged components
name: Tag and Export Components

on:
  push:
    branches: [main]

jobs:
  tag-and-export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/workflows/build
      - name: Hard-tag pending components
        run: bit tag --persist
      - name: Export components
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
          bit export
      - name: Updload bit.map
        uses: actions/upload-artifact@v3
        with:
          name: bitmap
          path: .bitmap